### ISSUE TITLE
Fix style/structure for links

### ISSUE THREAD

**Issue by cormacanderson** [lingdb/IELex2-CognaC#33]
Edited by @runjak:
All links in blue font (language names, meaning names) should also show the cursor switching to the hyperlink 'mode' when you hover over them (pointy finger in Windows, as already works for the magnifying glass icon link, or the cognate class letter).

**Comment by runjak** [comment]
This may likely be related to the fact that the current structure of many of these links is an input field inside a link where the link alone would suffice.

**Comment by runjak** [comment]
I think since the transition to bootstrap this issue has essentially been solved.
