### ISSUE TITLE
Move side column to header bar

### ISSUE THREAD

**Issue by cormacanderson** [lingdb/IELex2-CognaC#45]

**Comment by runjak** [comment]
This is the 'lead' issue for stuff that is labeled `Headers`.
Therefore I should solve this before getting on with the other `Headers` issues.
Also this issue is a good chance to switch to a new layout that builds on [bootstrap](getbootstrap.com).

**Comment by runjak** [comment]
Here is a draft of what a redesign should be organized like:
![foo](https://cloud.githubusercontent.com/assets/5417642/12717338/7a3f6dc8-c8e7-11e5-98c0-421a3bcd361d.png)

**Comment by runjak** [comment]
I'm currently working on a switch to a [bootstrap](https://getbootstrap.com/) based design,
and imagine that the transition there will happen in more or less two mayor steps:

1. Adjust the current structure of the page to bootstrap.
2. Adjust the top menu to fit the sketched one. I already had a draft for this, but discovered that the code for the top/side menu structure is scattered trough the templates and that the wanted menu structure will need additional changes that make more sense being realized later on.

That being said here is a screenshot from what I'm currently working on:
![screenshot_2016-02-11_12-10-31](https://cloud.githubusercontent.com/assets/5417642/12974987/a77fcfca-d0b8-11e5-8a23-dd7a71d26d9d.png)

**Comment by runjak** [comment]
The language table starts fitting together with the new bootstrap layout.
With commit 47473271de318a0f9a80ada33b764c4ff14e9dc2 it looks like this:
![langtab](https://cloud.githubusercontent.com/assets/5417642/12981700/0cc23584-d0e2-11e5-950d-15a82ba13f73.png)

**Comment by runjak** [comment]
After the template refinements we've had today and the deployment of last weeks work on transitioning the site to bootstrap I think this issue can be closed.

**Comment by runjak** [comment]
The draft for the search boxes and stuff however will still be helpful.
