### ISSUE TITLE
Add favicon (from attached jpg) to new IELex site

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/IELex2-CognaC#63]
![cognacglass](https://cloud.githubusercontent.com/assets/8819910/12752102/08240bf6-c9c1-11e5-9c51-115207bf819b.jpg)

**Comment by runjak** [comment]
I have a few questions about this:

1. This image appears to be related to an article on [howtotube](http://www.howtotube.com/what-is-cognac/).
   Do we have a license to use it, or do we need one?
2. I assume that we would like to use this image as both the favicon and the logo on the page header?
3. I would suggest making the white portion of the image (at least the part outside the glass) transparent rather than white. I think I can also add some transparency to the empty portion of the glass, but I'm not sure about that.

**Comment by PaulHeggarty** [comment]
Hmm, no idea about a licence.  OK, we can just get an image from the Wikipedia CognaC page or something.

**Comment by runjak** [comment]
The Wikipedia image for [cognac](https://en.wikipedia.org/wiki/File:Cognac_glass_-_tulip_shaped.JPG) is in the public domain and could therefore be used.
But I think it doesn't suit as a logo as well.
I think our options here are like this:
* Ask the website to figure out what license the image could have.
* Find a different image with a usable license.
* Create an image from scratch.
* There are [usable](http://www.shutterstock.com/pic-134738138/stock-photo-splash-of-cognac-in-glass-on-white-background.html?src=Z8VCM_HXlRsQ0NpsUFbmBQ-1-13) images available that we could by - [Shutterstock](http://www.shutterstock.com/subscribe) starts at 39€ for 5 images. I even think the [original](http://www.shutterstock.com/pic-183698486/stock-photo-splash-of-cognac-in-glass-isolated-on-white-background.html?src=Z8VCM_HXlRsQ0NpsUFbmBQ-1-72) comes from there.

**Comment by PaulHeggarty** [comment]
This really shouldn't waste our time.  For now, just put anything there.  The only reason is to help me and others identify tabs in our browsers, and distinguish between SndComp and CognaC.  Please just put any favicon there, but put something.

**Comment by runjak** [comment]
Ok, thanks for specifying.
I thought this issue was about rebranding or choosing a logo/icon in general.
Focussing on just the favicon should of course be possible in a shorter time.

**Comment by runjak** [comment]
I've created a simple logo and put that as the favicon and on the header bar of the current page.
This will get deployed with the next update.
The logo looks like this:
![CognaC logo](https://raw.githubusercontent.com/lingdb/cognac-logo/master/cognac_310px.png)
It is available in the [cognac-logo](https://github.com/lingdb/cognac-logo) repository in several resolutions and as a vector graphic.
