### ISSUE TITLE
In Lexemes table/forms, add new fields/columns

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/IELex2-CognaC#66]
Add fields to table:
Lex ID for web lookup 1
Lex ID for web lookup 2

Add corresponding columns to the lexemes forms (by language or by meaning).
Next to each field should be the corresponding link symbol, for the link formed as explained below.

Usually a short text string giving the exact spelling/form of this word, e.g. Spanish blanco, as the lookup term for the corresponding standard dictionary resource on the web, for this language.  In other cases, depending on the dictionary, it will have to be some other form, like the OED uses 14332 [http://www.oed.com/view/Entry/14332] to specify back as a noun meaning the back of a person (to distinguish this entry from other 'back' words, 14333 and others).
Presumably a short text string would work for both.

This is the string that will be combined with (follow) the new field in the languages table, for the main path to the website for the dictionary as a whole, e.g. for Spanish http://dle.rae.es/?w= . 
In combination they would give a link to:
[http://dle.rae.es/?w=blanco]
[http://www.oed.com/view/Entry/14332]

**Comment by runjak** [comment]
I've added the fields to the lexeme tables, but two things are missing:

1. I think it would make sense to display a link after the entry boxes where possible to make it easy to look up the current entry. Such a link should use `target="_blank"`.
2. The table has growing style problems.
This is still bearable on my machine when zooming out two levels.

![screenshot_2016-02-03_16-01-12](https://cloud.githubusercontent.com/assets/5417642/12786066/af6ce76a-ca8f-11e5-94b5-13d900645aa7.png)
But it gets increasingly difficult to work with the site on normal zoom levels.

**Comment by PaulHeggarty** [comment]
On point 1, yes.  An external link to a new tab.  With the usual 'arrow out of box' icon for that, as used on Wikipedia external links, for example.
On point 2, don't we know it.  This is why the sidebar to header thing is becoming so much a priority now.  Other solutions are to shrink the column labels wherever possible.  So I'll suggest some more.  Also, in the image you show, you're using the wrong column labels.  See next comment...

**Comment by PaulHeggarty** [comment]
The new columns here are headed with the label "This Lg lex rfc web path", but that is the name for the new fields needed in the *Languages* table, and their column headers in the Languages form.  Not here.
Here the columns should be for the fields "Lex ID for web lookup 1" and "Lex ID for web lookup 2" -- these are properties of, and fields in, the Lexemes table.  
The headers can be abbreviated, too:  Web dict ID 1, Web dict ID 2.  Should fit on two lines.
