### ISSUE TITLE
0 IELex2 Data Entry Website - Bugs!

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/IELex2-CognaC#7]

**Comment by m-scarborough** [comment]
Major functionality bug:  I've noticed in the testing of the new data-entry website cognate judgements can no longer be assigned from the individual meanings pages into their assigned classes (A, B, C, D, E, F, ... etc.).  New classes can still be created from the lexeme data overview pages, however when a new class is created additional lexemes can no longer be assigned to classes from the individual meanings page.  Effectively, cognate judgements cannot be made in the database until this is fixed.

**Comment by tonyakdewey** [comment]
I [@findell using Tonya's account] managed to add a new meaning (which I shouldn't be able to do).  It's xxxx on the word list and needs to be deleted.

**Comment by cormacanderson** [comment]
@findell, @tonyakdewey , I have changed the user permissions and deleted the xxxx meaning

**Comment by leszekjocz** [comment]
If I open a list for a language that has no entries yet, the list looks like that:

![bug](https://cloud.githubusercontent.com/assets/16056017/11535311/9ddbfcd2-9913-11e5-9361-ac53304b4be2.png)

So I have to enter the date **completely the same way** as on the **old page** and I gain **no** new functionality. Is it possible to generate an empty table in such cases? Or to add nonsence enties likie "xyz" to the "lexeme" fields?

**Comment by runjak** [comment]
Ah, thanks for highlighting this!

**Comment by tonyakdewey** [comment]
Is it possible to select a view with the things marked 'Not Swadesh Term' excluded?  Just because I don't want to spend ages entering phonemic/phonetic transcriptions for things that may eventually be deleted anyway.  Also, I want to be able to get an accurate lexeme count (which is currently not possible for many of my languages).
