### ISSUE TITLE
Cognate set count for each meaning

### ISSUE THREAD

**Issue by cormacanderson** [lingdb/IELex2-CognaC#74]
This should appear as a field in the meanings table. It should count the number of cognate sets associated to each meaning and display the number.

**Comment by runjak** [comment]
Note to myself:
We decided that we want the edit ability for meaning metadata that currently resides under `/meaning/<meaning>/edit/` to be editable from the general meaning table that resides at `/wordlist/<wordList>/`.

**Comment by runjak** [comment]
The current solution for this involves lookups over several tables:

* For each meaning we need to figure out all the lexemes.
* For each lexeme we need to look at the cognate judgements.
* For all cognate judgements we need to get the distinct count of cognate class ids.

This makes the meaning table a bit slower to build, but not that much slower than the other tables. See #84 for further discussion on site performance.
The current solution will be pushed soon and shall close this issue.
