### ISSUE TITLE
Set default view to hide, not show, non-Swadesh terms

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/IELex2-CognaC#78]
Also rename the button to "Show" or "Hide", toggling between those depending on the value of the filter.  So the default should be "Show", since the filter should be set to hide them.  
And put the toggle button immediately under the Not Sw column header, in what will be the new filter bar.

**Comment by runjak** [comment]
For this issue it makes sense to start working on the new filter bar that has been requested several times. I'm aiming to use the popular jQuery plugin [DataTables](https://www.datatables.net/) for this and to solve the issues #54,#86 and #89 in the same batch.
