### ISSUE TITLE
In 1-Mg All-Lgs form, colour record rows by cognate class.

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/IELex2-CognaC#80]
This should replace the current colouring just by alternating rows.
This will mean that we need not just two alternating colours, as now, but many, one for each cognate class alias letter, so in some cases even more than 26 colours.  Presumably there exists some default listing of contrasting colours that you can use -- does Bootstrap have its own?

**Comment by runjak** [comment]
There are sets of [maximally dissimilar colors](https://graphicdesign.stackexchange.com/a/3815/44780) that I feel are useful for this issue and for #81 as well since they should both rely on the same set of colors.

**Comment by PaulHeggarty** [comment]
We need pastel-type fairly light background colours, so we can't use fully distinct colours in dark shades.  So I've come up with the following list.  First is my 'index', which gives six distinct colours, then six more intermediate between those, and so on up to 24.  Use them in this order.  Two exceptions, special colouring:
Any lexeme that has no cognate class assigned should be white, FFFFFF.
Any lexeme that is the only member of its cognate class (= class with total member lexemes = 1) should be grey:  D2D2D2
 1 	 E7CBCB 
 2 	 CBE7E7 
 3 	 E7D2CB 
 4 	 CBE0E7 
 5 	 E7D9CB 
 6 	 CBD9E7 
 7 	 E7E0CB 
 8 	 CBD2E7 
 9 	 E7E7CB 
 10 	 CBCBE7 
 11 	 E0E7CB 
 12 	 D2CBE7 
 13 	 D9E7CB 
 14 	 D9CBE7 
 15 	 D2E7CB 
 16 	 E0CBE7 
 17 	 CBE7CB 
 18 	 E7CBE7 
 19 	 CBE7D2 
 20 	 E7CBE0 
 21 	 CBE7D9 
 22 	 E7CBD9 
 23 	 CBE7E0 
 24 	 E7CBD2

**Comment by PaulHeggarty** [comment]
If you know a way of quickly doing us a demo of what those shades look like in that order, please do so and let us check!
Also, the grey and white requests are not so urgent, if they are going to delay you.

**Comment by runjak** [comment]
Here is a preview of the chosen colors:
![colors](https://cloud.githubusercontent.com/assets/5417642/13255581/0fe3836c-da47-11e5-9a95-b216af69e428.png)

**Comment by PaulHeggarty** [comment]
Hmmm, not as nice as I'd hoped -- many are too similar to each other.  Time for another think, perhaps we could skip some of the intermediate colours but we'd end up with fewer.
In any case, these values can be changed later, but please do get on with the programming to do this, and we can fine-tune the shades later.

**Comment by runjak** [comment]
I've implemented this issue and #81 and will roll them out soon.
I think the coloring is already an improvement on the current situation and the colors are indeed adjustable easily later.
